jobs:
  python_unittests:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}
    - name: install tox
      run: pip install 'virtualenv<20.22.0' 'tox<4.5.0'
    - name: add mandatory git remote
      run: git remote add hpcugent https://github.com/hpcugent/vsc-ldap.git
    - name: install dependencies
      run: sudo apt-get install -y libsasl2-dev libldap2-dev
    - name: Run tox
      run: tox -e py
    strategy:
      matrix:
        python:
        - 3.6
        - 3.9
name: run python tests
'on':
- push
- pull_request
